version: "3.8"
services:
  avenger-clinic:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - avenger_clinic_net
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=RahasiaBanget123
      - POSTGRES_DATABASE=avenger_clinic_db
    volumes:
      - avenger-clinic-volume:/var/lib/postgresql/data
    networks:
      - avenger_clinic_net
volumes:
  avenger-clinic-volume:
networks:
  avenger_clinic_net:
    driver: bridge
